package com.example.refreshtokenapp.data.remote.login;

public class Data{
	private String portalType;
	private int expiryTimeInMin;
	private CallcenterRole callcenterRole;
	private UserData userData;
	private int isAutogeneratedPassword;
	private String message;
	private String email;
	private String encryptedPassword;
	private String token;
	private String refreshToken;

	public String getPortalType(){
		return portalType;
	}

	public int getExpiryTimeInMin(){
		return expiryTimeInMin;
	}

	public CallcenterRole getCallcenterRole(){
		return callcenterRole;
	}

	public UserData getUserData(){
		return userData;
	}

	public int getIsAutogeneratedPassword(){
		return isAutogeneratedPassword;
	}

	public String getMessage(){
		return message;
	}

	public String getEmail(){
		return email;
	}

	public String getEncryptedPassword(){
		return encryptedPassword;
	}

	public String getToken(){
		return token;
	}

	public String getRefreshToken(){
		return refreshToken;
	}
}
