package com.example.refreshtokenapp.data.remote.login;

import java.util.List;

public class UserData{
	private String empId;
	private String lastName;
	private int isPriorityLogin;
	private String gender;
	private String adminType;
	private String distributorId;
	private String fullName;
	private int isAutogeneratedPassword;
	private String firstName;
	private String nextPasswordChangeDate;
	private String warehouseId;
	private String brandId;
	private String id;
	private String designation;
	private List<Object> region;
	private String email;

	public String getEmpId(){
		return empId;
	}

	public String getLastName(){
		return lastName;
	}

	public int getIsPriorityLogin(){
		return isPriorityLogin;
	}

	public String getGender(){
		return gender;
	}

	public String getAdminType(){
		return adminType;
	}

	public String getDistributorId(){
		return distributorId;
	}

	public String getFullName(){
		return fullName;
	}

	public int getIsAutogeneratedPassword(){
		return isAutogeneratedPassword;
	}

	public String getFirstName(){
		return firstName;
	}

	public String getNextPasswordChangeDate(){
		return nextPasswordChangeDate;
	}

	public String getWarehouseId(){
		return warehouseId;
	}

	public String getBrandId(){
		return brandId;
	}

	public String getId(){
		return id;
	}

	public String getDesignation(){
		return designation;
	}

	public List<Object> getRegion(){
		return region;
	}

	public String getEmail(){
		return email;
	}
}